[project]
name = 'Meta-Ethical-Framework-Evolution-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.ethical-framework-coherence]
path = 'contracts/ethical-framework-coherence.clar'
clarity_version = 2
epoch = 2.5

[contracts.moral-axiom-generation]
path = 'contracts/moral-axiom-generation.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
